<?php

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

function webcare_wp_status_show_log(){
        // Directory for logs
        $log_dir = trailingslashit( plugin_dir_path(__FILE__) . 'log' );

        // Check if the log folder exists, create if not
        if (!is_dir($log_dir)) {
            mkdir($log_dir, 0755, true);
        }
        webcare_wp_status_protect_log_dir( $log_dir );

        // Only show logs generated by this site (keeps multisite installs from
        // leaking each other's plugin/theme/user data in the shared log folder)
        $site_host = sanitize_file_name( preg_replace( '#^https?://#', '', site_url() ) );

        // Display all JSON logs in a table
        $log_files = glob( $log_dir . $site_host . '-*.json' );
        usort($log_files, function($a, $b) {
            return filemtime($b) - filemtime($a); // Descending order
        });

        echo '<div class="webcare-wp-status-section-title">';
        echo '<span class="dashicons dashicons-list-view"></span>';
        echo '<h2 style="margin:0;">System Info Logs';
        if ( $log_files ) {
            echo ' <span class="webcare-wp-status-count">(' . esc_html( count( $log_files ) ) . ')</span>';
        }
        echo '</h2>';
        echo '</div>';

        if ($log_files) {
            echo '<table class="widefat fixed striped webcare-wp-status-table">';
            echo '<thead><tr><th>Date</th><th>Systems</th><th>Pages and Posts</th><th>Plugins</th><th>Front Page Files</th><th>Folder Size</th><th>Users Count</th><th>Actions</th></tr></thead>';
            echo '<tbody>';

            foreach ($log_files as $file) {
                $json_data = file_get_contents($file);
                $data = json_decode($json_data, true);

                if ($data) {
                    $filename = basename($file);
                    $theme_badge_class = ( 'Active' === $data['theme_status'] ) ? 'is-active' : 'is-inactive';

                    echo '<tr>';
                    echo '<td>' . esc_html( mysql2date( 'd M Y h:ia', $data['date'] ) ) . '</td>';

                    // Systems information
                    echo '<td><ul class="webcare-wp-status-list">';
                    echo '<li><span class="label">WordPress:</span> ' . esc_html($data['wordpress_version']) . '</li>';
                    echo '<li><span class="label">PHP:</span> ' . esc_html($data['php_version']) . '</li>';
                    echo '<li><span class="label">MySQL:</span> ' . esc_html($data['mysql_version']) . '</li>';
                    echo '<li><span class="label">Theme:</span> ' . esc_html($data['theme']) . ' <span class="webcare-wp-status-badge ' . esc_attr($theme_badge_class) . '">' . esc_html($data['theme_status']) . '</span></li>';
                    echo '<li><span class="label">Parent theme:</span> ' . esc_html($data['parent_theme']) . ' (' . esc_html($data['parent_theme_version']) . ')</li>';
                    echo '</ul></td>';

                    // Posts and pages information
                    echo '<td><ul class="webcare-wp-status-list">';
                    echo '<li><span class="label">Pages published:</span> ' . esc_html($data['pages_count']) . '</li>';
                    echo '<li><span class="label">Pages draft:</span> ' . esc_html($data['pages_draft_count']) . '</li>';
                    echo '<li><span class="label">Posts published:</span> ' . esc_html($data['posts_count']) . '</li>';
                    echo '<li><span class="label">Posts draft:</span> ' . esc_html($data['posts_draft_count']) . '</li>';
                    echo '<li><span class="label">Custom posts:</span> ' . esc_html($data['published_custom_posts']) . '</li>';
                    echo '</ul></td>';

                    // Plugins information
                    echo '<td><ul class="webcare-wp-status-list">';
                    echo '<li><span class="label">Total:</span> ' . esc_html($data['plugins_count']) . '</li>';
                    echo '<li><span class="label">Active:</span> ' . esc_html($data['active_plugins_count']) . '</li>';
                    echo '<li><span class="label">Inactive:</span> ' . esc_html($data['inactive_plugins_count']) . '</li>';
                    echo '</ul></td>';

                    echo '<td>CSS: ' . esc_html($data['css_js_count']['css']) . ' / JS: ' . esc_html($data['css_js_count']['js']) . '</td>';

                    // Folder size information
                    echo '<td><ul class="webcare-wp-status-list">';
                    echo '<li><span class="label">WP folder:</span> ' . esc_html($data['wp_folder_size']) . '</li>';
                    echo '<li><span class="label">Plugins:</span> ' . esc_html($data['plugin_folder_size']) . '</li>';
                    echo '<li><span class="label">Media:</span> ' . esc_html($data['upload_folder_size']) . '</li>';
                    echo '<li><span class="label">Database:</span> ' . esc_html($data['db_size']) . '</li>';
                    echo '</ul></td>';

                    // Users count, broken down by role
                    echo '<td><ul class="webcare-wp-status-list">';
                    if ( is_array( $data['users_count'] ) ) {
                        echo '<li><span class="label">Total:</span> ' . esc_html( $data['users_count']['total'] ) . '</li>';
                        echo '<li><span class="label">Admin:</span> ' . esc_html( $data['users_count']['admin'] ) . '</li>';
                        echo '<li><span class="label">Editor:</span> ' . esc_html( $data['users_count']['editor'] ) . '</li>';
                        echo '<li><span class="label">Others:</span> ' . esc_html( $data['users_count']['others'] ) . '</li>';
                        if ( ! empty( $data['users_count']['hidden'] ) ) {
                            echo '<li><span class="label">Hidden:</span> ' . esc_html( $data['users_count']['hidden'] ) . '</li>';
                        }
                    } else {
                        echo '<li><span class="label">Total:</span> ' . esc_html( $data['users_count'] ) . '</li>';
                    }
                    echo '</ul></td>';

                    // Actions
                    $download_url = wp_nonce_url(
                        admin_url( 'admin-post.php?action=webcare_download_log&file=' . rawurlencode( $filename ) ),
                        'webcare_download_log_' . $filename
                    );
                    $delete_url = wp_nonce_url(
                        admin_url( 'tools.php?page=wp_status&delete_log=' . rawurlencode( $filename ) ),
                        'webcare_delete_log_' . $filename
                    );

                    echo '<td><div class="webcare-wp-status-actions">';
                    echo '<a href="' . esc_url( $download_url ) . '" class="button button-small"><span class="dashicons dashicons-download"></span> Download</a>';
                    echo '<a href="' . esc_url( $delete_url ) . '" class="button button-small button-danger" onclick="return confirm(\'Delete this log file?\');"><span class="dashicons dashicons-trash"></span> Delete</a>';
                    echo '</div></td>';

                    echo '</tr>';
                }
            }

            echo '</tbody>';
            echo '</table>';
        } else {
            echo '<div class="webcare-wp-status-empty">';
            echo '<span class="dashicons dashicons-info-outline" style="font-size:32px;width:32px;height:32px;display:block;margin:0 auto 8px;"></span>';
            echo '<p>No log files found yet. Click <strong>&ldquo;Create a New Log&rdquo;</strong> above to generate your first one.</p>';
            echo '</div>';
        }
}
